version: '3.9'
services:
  go-sample:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9999:80"
    image: go-sample
    restart: always
    networks:
      - web


networks:
  web: