# Default values for charts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


appName: go-sample-app
deploymentName: go-sample-deployment
replicaCount: 1

image:
  repository: melsheikh91/go-sample
  pullPolicy: IfNotPresent
  tag: "1.3"

service:
  name: go-sample-service
  type: NodePort
  port: 80

